name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test HTML Proficiency
      id: test-html-proficiency
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test HTML Proficiency
        setup-command: pip install webcode-tk file-clerk pytest
        command: pytest tests/test_html_requirements.py
        timeout: 10
        max-score: 1
    - name: Test CSS Proficiency
      id: test-css-proficiency
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test CSS Proficiency
        setup-command: pip install webcode-tk file-clerk pytest
        command: pytest tests/test_css_requirements.py
        timeout: 10
        max-score: 1
    - name: Test Validity
      id: test-validity
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Validity
        setup-command: pip install webcode-tk file-clerk pytest
        command: pytest tests/test_validity.py -W default -v
        timeout: 10
        max-score: 1
    - name: Test Exceeds
      id: test-exceeds
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Exceeds
        setup-command: pip install webcode-tk file-clerk pytest
        command: pytest tests/test_exceeds_requirements.py
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-HTML-PROFICIENCY_RESULTS: "${{steps.test-html-proficiency.outputs.result}}"
        TEST-CSS-PROFICIENCY_RESULTS: "${{steps.test-css-proficiency.outputs.result}}"
        TEST-VALIDITY_RESULTS: "${{steps.test-validity.outputs.result}}"
        TEST-EXCEEDS_RESULTS: "${{steps.test-exceeds.outputs.result}}"
      with:
        runners: test-html-proficiency,test-css-proficiency,test-validity,test-exceeds
